### ISSUE TITLE
Custom layout

### ISSUE THREAD

**Issue by YousefED** [jerrywu001/vitepress-plugin-sandpack#1]
Hi @jerrywu001 !

Thanks for this great plugin.

I want to use a custom layout for Sandpack. In my case, I want to display the editor above the results, instead of the default side-by-side. Is this possible with `vitepress-plugin-sandpack`?

**Comment by jerrywu001** [comment]
Hi, you can add some CSS:

- docs/.vitepress/theme/sandpack.css

```css
.sp-layout > .sp-stack {
    min-width: 100% !important;
}
```

- docs/.vitepress/theme/index.ts

```diff
import DefaultTheme from 'vitepress/theme';
+import { Sandbox } from 'vitepress-plugin-sandpack';
+import './sandpack.css';

export default {
  ...DefaultTheme,
  enhanceApp(ctx) {
    DefaultTheme.enhanceApp(ctx);
+    ctx.app.component('Sandbox', Sandbox);
  },
}
```

**Comment by YousefED** [comment]
Thanks!

**Comment by YousefED** [comment]
Hi @jerrywu001 !

Your solution worked for changing the order, but now I'm running into a different case (showing multiple preview panes).

In Sandpack, this is possible with a custom layout: https://sandpack.codesandbox.io/docs/advanced-usage/components#layout

Do you know if this is also possible with your plugin?

Thanks,

**Comment by jerrywu001** [comment]
> Hi @jerrywu001 !
> 
> Your solution worked for changing the order, but now I'm running into a different case (showing multiple preview panes).
> 
> In Sandpack, this is possible with a custom layout: https://sandpack.codesandbox.io/docs/advanced-usage/components#layout
> 
> Do you know if this is also possible with your plugin?
> 
> Thanks,

Sorry, not yet, just the default sandpack. Maybe you can custom your own with [sandpack-vue3](https://www.npmjs.com/package/sandpack-vue3) , the API is same as `sandpack-react` @YousefED

**Comment by jerrywu001** [comment]
there is a custom demo with `sandpack-vue3`

https://github.com/starbeamjs/docs/blob/main/src/tutorial/-components/Code/Code.vue

@YousefED
