### ISSUE TITLE
Loading a local JS file

### ISSUE THREAD

**Issue by h7ml** [jerrywu001/vitepress-plugin-sandpack#2]
May I ask if it is possible to load a local JS file for display? If so, how can I use this feature?

**Comment by jerrywu001** [comment]
感谢大佬，非常好的建议，我来看看有什么解决办法

**Comment by h7ml** [comment]
目前在这里看到了 有md版本的 https://notes.fe-mm.com/fe/coding/

https://github.com/maomao1996/mm-notes/blob/master/docs/fe/coding/index.md?plain=1#L17

**Comment by jerrywu001** [comment]
https://vitepress-sandbox.js-bridge.com/basic-usage/snippets.html

@h7ml v0.2.3
