### ISSUE TITLE
开发dev环境和build环境表现不一致

### ISSUE THREAD

**Issue by haibins** [jerrywu001/vitepress-plugin-sandpack#4]
开发dev环境和build环境表现不一致问题

dev环境
<img width="1422" alt="image" src="https://github.com/jerrywu001/vitepress-plugin-sandpack/assets/29914762/b6de1665-4506-445c-b551-0f9538fecd75">

build环境
<img width="1459" alt="image" src="https://github.com/jerrywu001/vitepress-plugin-sandpack/assets/29914762/a12c94c7-1c35-4ce4-b448-8981a32fcceb">

今天构建突然发现构建后显示异常，请问一下是什么问题？线上构建地址可以访问 https://npm.futurefab.cn/xchart/example.html
build后产物表现为有部分sandbox显示错位，nav重复

**Comment by haibins** [comment]
之前构建好像都是正常的，今天也没有升级版本，突然发现本地构建也异常了

**Comment by haibins** [comment]
https://github.com/haibins/vitepress-starter 在这个demo里`build`可以重现一下场景，`build`后第一次加载是正常的，刷新后就不正常了

**Comment by jerrywu001** [comment]
![image](https://github.com/jerrywu001/vitepress-plugin-sandpack/assets/12525415/40ccdc86-d3d8-4ff3-8bb5-f657bc0f36d4)

![image](https://github.com/jerrywu001/vitepress-plugin-sandpack/assets/12525415/33ac1e04-6dac-4f37-8aaf-62dc5014707d)

我是node v16.20

**Comment by jerrywu001** [comment]
你加"type": module"试试

**Comment by haibins** [comment]
可以直接加吗
<img width="2220" alt="image" src="https://github.com/jerrywu001/vitepress-plugin-sandpack/assets/29914762/7a6b58c8-986b-4e85-aa25-278c3033690a">

**Comment by haibins** [comment]
node版本：

<img width="486" alt="image" src="https://github.com/jerrywu001/vitepress-plugin-sandpack/assets/29914762/b684c106-7f8c-49c9-8375-706bd3ed8baa">

有出现这样的错位吗

<img width="822" alt="image" src="https://github.com/jerrywu001/vitepress-plugin-sandpack/assets/29914762/a16967ad-da41-4368-a11d-9ac08cc7d050">

**Comment by haibins** [comment]
> 

这个报错是因为整个是个空的注释，就是截图的框框没有渲染出sandbox的位置，浏览器版本是最新的

**Comment by haibins** [comment]
刚刚提交的就是完整的线上例子，可以重新拉一下。可以`run docs:dev`和`run docs:build`对比一下试试

**Comment by jerrywu001** [comment]
![image](https://github.com/jerrywu001/vitepress-plugin-sandpack/assets/12525415/376a95f3-e5f7-4178-9585-907cc7f7c325)
没问题啊

**Comment by jerrywu001** [comment]
加下：

  "type": "module",

```json
{
  "name": "vitepress-starter",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "type": "module",
  "scripts": {
    "dev": "vitepress dev docs",
    "build": "vitepress build docs",
    "serve": "vitepress serve docs"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "devDependencies": {
    "vitepress": "1.0.0-beta.6",
    "vitepress-plugin-sandpack": "^0.3.0",
    "vue": "^3.3.4"
  },
  "dependencies": {
    "@xchart/vue": "^0.1.13"
  }
}

```

**Comment by haibins** [comment]
刷新几次也没问题吗？我这里是这样的
<img width="1424" alt="image" src="https://github.com/jerrywu001/vitepress-plugin-sandpack/assets/29914762/6d17fc1c-e5b2-46b7-964f-e408601b3b3a">

**Comment by jerrywu001** [comment]
我还以为你说的那个报错呢？这个确实有，之前也发现过，正常点过去没问题

**Comment by haibins** [comment]
> 加下：
> 
> ` "type": "module",`
> 
> 删掉lock文件, node_modules, 重新npm i 试试
> 
> ```json
> {
>   "name": "vitepress-starter",
>   "version": "1.0.0",
>   "description": "",
>   "main": "index.js",
>   "type": "module",
>   "scripts": {
>     "dev": "vitepress dev docs",
>     "build": "vitepress build docs",
>     "serve": "vitepress serve docs"
>   },
>   "keywords": [],
>   "author": "",
>   "license": "ISC",
>   "devDependencies": {
>     "vitepress": "1.0.0-beta.6",
>     "vitepress-plugin-sandpack": "^0.3.0",
>     "vue": "^3.3.4"
>   },
>   "dependencies": {
>     "@xchart/vue": "^0.1.13"
>   }
> }
> ```

这样试了一下没问题。但是我是`pnpm`的，好像是这个区别

**Comment by haibins** [comment]
用`pnpm i`，然后`run build`就是我这个样子了

**Comment by jerrywu001** [comment]
那就用npm吧，pnpm确实有问题

下面的报错你怎么跳过去的？？？

![image](https://github.com/jerrywu001/vitepress-plugin-sandpack/assets/12525415/bbbb6fbb-9360-438a-bf45-d33a76370056)

**Comment by jerrywu001** [comment]
use v0.3.2

**Comment by jerrywu001** [comment]
remove `"type": "module"`

or 

https://vitepress-sandbox.js-bridge.com/get-started/introduction.html#problem-this-package-is-esm-only

**Comment by haibins** [comment]
> use v0.3.2
> 
> 可以使用最新的vitepress了，如果出现markdown-it-container not fund, 执行 `pnpm add markdown-it-container` @haibins
> 
> https://vitepress-sandbox.js-bridge.com/get-started/introduction.html#problem-this-package-is-esm-only

markdown-it-container 这个确实是漏了，我重新改了一下版本号，用`pnpm i`可以复现了，要锁定`0.3.0`版本，大佬可以帮看看吗，拉取一下用`pnpm i`

**Comment by jerrywu001** [comment]
use v1.0.3 or v0.3.2

online demo:

https://stackblitz.com/edit/vitejs-vite-79ocfq?file=package.json

**Some problems can see:**

https://vitepress-sandbox.js-bridge.com/get-started/install.html#install-package

https://vitepress-sandbox.js-bridge.com/get-started/introduction.html#problem-this-package-is-esm-only

**Comment by haibins** [comment]
用 `v1.0.3`  没有这个现象了，页面正常了，但是我看最近的版本修改好像也没什么改动，是什么导致的呢

**Comment by jerrywu001** [comment]
> 用 `v1.0.3` 没有这个现象了，页面正常了，但是我看最近的版本修改好像也没什么改动，是什么导致的呢

![image](https://github.com/jerrywu001/vitepress-plugin-sandpack/assets/12525415/48df3492-97af-4915-9aa6-cc279edda24d)
