### ISSUE TITLE
Language `#hidden` not found

### ISSUE THREAD

**Issue by BlackRam-oss** [jerrywu001/vitepress-plugin-sandpack#6]
in the new version of vitepress 1.4.3, the library gives the following error:

```
Language `#hidden` not found, you may need to load it first
ShikiError: Language `#hidden` not found, you may need to load it first
```

**Comment by jerrywu001** [comment]
![image](https://github.com/user-attachments/assets/7fc1866b-3945-4902-9d6b-f297cb2c5ffb)

see: https://vitepress-sandbox.js-bridge.com/basic-usage/hidden.html
