### ISSUE TITLE
运行报错

### ISSUE THREAD

**Issue by haibins** [jerrywu001/vitepress-plugin-sandpack#7]
![image](https://github.com/user-attachments/assets/37cf36a1-c0e1-4880-a89d-cf05d9e8fdf4)
请问下这个是不能正常使用了吗

**Comment by jerrywu001** [comment]
受限于[sandpack-client](https://sandpack.codesandbox.io/docs/advanced-usage/client)，毕竟是国外产品，服务对于国内来说可能不是很稳定
